services:
  - type: web
    name: youtube-shorts-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py autonomous
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free

